# Generated by Django 4.0.6 on 2022-07-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
